name: Release Package

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.9
          cache: true

      - name: Setup PDM bump plugin
        run: |
          pdm self add pdm-bump

      - name: Detect and tag new version
        id: check-version
        uses: salsify/action-detect-and-tag-new-version@v2.0.3
        with:
          version-command: |-
            pdm show --version

      - name: Bump version for developmental release
        if: "! steps.check-version.outputs.tag"
        run: |
          dev_version="$(echo $(pdm show --version).dev$(date +%s))"
          pdm bump to "$dev_version"

      - name: Install dependencies with PDM
        run: |
          pdm install

      - name: Build package
        run: |
          pdm build

      - name: Publish package on PyPI
        if: steps.check-version.outputs.tag
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish package on TestPyPI
        if: "! steps.check-version.outputs.tag"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v5.25.0
        with:
          publish: ${{ steps.check-version.outputs.tag != '' }}
          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
